events {
    
}
http {
  server {
    listen 80;

    location /api/identity/ {
      proxy_pass http://identity-api:4001/;
    }

    location /api/ambassade/ {
      proxy_pass http://ambassade-api:4002/;
    }

    location /api/communaute/ {
      proxy_pass http://communaute-api:4003/;
    }
  }
}
